### ISSUE TITLE
Minors corrections

### ISSUE THREAD

**Issue by callbasher** [ArnaudFnr/GDPR-RGPD#1]
In file RGPD(fr).pdf:
- remove one of 2 dates (page 1)
- modify text color (page 2)
- modify color of dash (pages 4, 7, 10, 13)
- modify color of number page (Layout)
- add a delimiter between names (Layout)
- coherence between dash (pages 4, 6, 7, 10) and page number (page 10)

Suggestion:
- add dash page 5

**Comment by ArnaudFnr** [comment]
I don't agree with changing the color in page 2 because it is symmetrical to the overall strcuture of the slide.
